repos:
  - repo: local
    hooks:
      - id: flake8
        name: Run flake8
        entry: poetry run flake8 .
        language: system
        types: [python]

      - id: mypy
        name: Run mypy
        entry: poetry run mypy .
        language: system
        types: [python]

      - id: black
        name: Run black
        entry: poetry run black --check .
        language: system
        types: [python]

      - id: isort
        name: Run isort
        entry: poetry run isort --check-only .
        language: system
        types: [python]
