repos:
  - repo: local
    hooks:
      - id: flake8
        name: Run flake8
        entry: bash -c "echo 'Running flake8'; flake8 .; echo 'flake8 done'"
        language: system
        types: [python]

      - id: mypy
        name: Run mypy
        entry: bash -c "echo 'Running mypy'; mypy .; echo 'mypy done'"
        language: system
        types: [python]

      - id: black
        name: Run black
        entry: bash -c "echo 'Running black'; black --check .; echo 'black done'"
        language: system
        types: [python]

      - id: isort
        name: Run isort
        entry: bash -c "echo 'Running isort'; isort --check-only .; echo 'isort done'"
        language: system
        types: [python]
