name: Post-Merge Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy black isort

    - name: Run flake8
      run: flake8 your_code_directory/

    - name: Run mypy
      run: mypy your_code_directory/

    - name: Run black
      run: black --check your_code_directory/

    - name: Run isort
      run: isort --check-only your_code_directory/
